config/routes.rb
Rails.application.routes.draw do
  get 'parcel/:id' => 'parcel#show', as: :parcel
  root 'station#index'
  get 'stations' => 'station#index'
  get 'stations/:id' => 'station#show', as: :station

end

app/models/district.rb
class District < ActiveRecord::Base
end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
	def as_point
		"ST_GeomFromText('#{geom.to_s}')"
	end
	
	def center_as_latlng
		geom.centroid.to_s[/\((.+)\)/,1].split(' ').reverse.join(', ')
	end

	def as_geojson
		RGeo::GeoJSON.encode(geom).to_json
	end
	def zone
		sql =<<SQL
			SELECT
				*
			FROM
				districts d
			WHERE
				ST_CoveredBy(
					 #{as_point},
					 d.geom


					-- d.geom,
					-- #{as_point}
				)
SQL
		@x = ActiveRecord::Base.connection.execute(sql)
		@geo_json = @x.values
	end
end


# ST_Boundary, ST_ContainsProperly, ST_Covers,ST_CoveredBy, ST_Equals,ST_Within

app/models/station.rb
class Station < ActiveRecord::Base
	def as_point
		"ST_GeomFromText('#{geom.to_s}')"
	end

	def as_latlng
		geom.to_s[/\((.+)\)/,1].split(' ').reverse.join(', ')
	end

	def name
		station.titleize
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parcel_controller.rb
class ParcelController < ApplicationController
  def show
  	@parcel = Parcel.find_by_gid(params[:id])
  end

  def index
  	Parcel.count
  end
end

app/controllers/point_controller.rb
class PointController < ApplicationController
  def index
  	sql =<<SQL
		  	SELECT row_to_json(fc)
				 FROM ( SELECT 'FeatureCollection' As type, array_to_json(array_agg(f)) As features
				 FROM (SELECT 'Feature' As type
				    , ST_AsGeoJSON(p.geom)::json As geometry
				    , row_to_json((SELECT l FROM (SELECT d.znlabel) As l
				      )) As properties
				   FROM parcels p
				LEFT JOIN
					districts d
				ON
					ST_Contains(d.geom, p.geom)
				WHERE
					ST_DWithin(p.geom::geography, ST_GeomFromText('POINT(-122.267047 37.8290643)')::geography, 804) ) As f )  As fc;

SQL
		@x = ActiveRecord::Base.connection.execute(sql)
		@geo_json = @x.values[0][0].gsub('\"', '"')
  end

  def show
  end
end

app/controllers/station_controller.rb
class StationController < ApplicationController
  def show
  	@station = Station.find(params[:id])
  	sql =<<SQL
		  	SELECT row_to_json(fc)
				 FROM ( SELECT 'FeatureCollection' As type, array_to_json(array_agg(f)) As features
				 FROM (SELECT 'Feature' As type
				    , ST_AsGeoJSON(p.geom)::json As geometry
				    , row_to_json((SELECT l FROM (SELECT d.znlabel, p.gid) As l
				      )) As properties
				   FROM parcels p
				LEFT JOIN
					districts d
				ON
					ST_Contains(d.geom, p.geom)
				WHERE
					ST_DWithin(p.geom::geography, #{@station.as_point}::geography, 804) ) As f )  As fc;

SQL
		puts @sql
		@sql = sql
		@x = ActiveRecord::Base.connection.execute(sql)
		@geo_json = @x.values[0][0].gsub('\"', '"')
  end

  def index
  	@stations = Station.where(gid: 4..11)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/station_helper.rb
module StationHelper
	def static_map(marker)
		root = 'https://maps.googleapis.com/maps/api/staticmap'
		key = 'AIzaSyBtxj21zNBckjM1RCBV8hpb8dRXyEngkcE'
		"#{root}?markers=#{marker}&zoom=14&size=320x320&key=#{key}"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ozone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parcel/index.html.erb
<h1>Parcel#index</h1>
<p>Find me in app/views/parcel/index.html.erb</p>

app/views/parcel/show.html.erb
<link rel="stylesheet" href="//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<script src="//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<style type="text/css">#map { height: 400px; } </style>
<div id="map"></div>

<b>Zone as raw: </b><%= @parcel.zone %>
<br>
<b>parcel as json: </b><%= @parcel.to_json %>
<br>

<script type="text/javascript">
	var map = L.map('map').setView([<%= @parcel.center_as_latlng %>], 16);
	L.tileLayer('https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png', {
    maxZoom: 18
	}).addTo(map);

	L.geoJson(<%= raw @parcel.as_geojson %>).addTo(map);

	<% if !@parcel.zone[0].nil? %>
		L.geoJson(<%= raw District.find(@parcel.zone[0][0].to_i).as_geojson %>).addTo(map);
	<% end %>

</script>

<a href="/district/470">Telegraph in Temescal</a>
<a href="/district/466">Longfellow core</a>
<a href="/district/653">Chinatown</a>

app/views/point/index.html.erb
<link rel="stylesheet" href="//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<script src="//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<style type="text/css">
	#map { height: 400px; } .legend{ list-style: none none; }
	.legend li.white{ color: white; }
	.legend li{
		display: inline;padding: 3px 3px 3px 3px;
	}
</style>
<h1>Parcels around MacArthur Station</h1>
<ul class="legend">
	<li style="background-color:#88CC88">RM-1</li>
	<li style="background-color:#55AA55">RM-2</li>
	<li class="white" style="background-color:#116611">RM-3</li>
	<li class="white" style="background-color:#004400">RM-3/C</li>
	<li style="background-color:#669999">RM-4</li>
	<li style="background-color:#407F7F">RU-1</li>
	<li class="white" style="background-color:#226666">RU-3</li>
	<li class="white" style="background-color:#0D4D4D">RU-4</li>
	<li class="white" style="background-color:#003333">RU-5</li>
	<li class="white" style="background-color:#13073A">CC-2</li>
	<li style="background-color:#FFAAAA">CN-2</li>
	<li style="background-color:#D46A6A">CN-3</li>
	<li style="background-color:#AA3939">CN-3/D-KP-1</li>
	<li class="white" style="background-color:#801515">D-KP-4</li>
	<li style="background-color:#FFDB58">S-1</li>
	<li style="background-color:#FFC900">S-15</li>
</ul>
<div id="map"></div>

<script type="text/javascript">
	maca_bart = "-122.267047 37.8290643"
	// var map = L.map('map').setView([-122.267047, 37.8290643], 13);
	var map = L.map('map').setView([37.8290643, -122.267047], 13);
	L.tileLayer('https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png', {
    maxZoom: 18
	}).addTo(map);
	L.geoJson(<%= raw @geo_json %>,  {
    style: function(feature) {
        switch (feature.properties.znlabel) {
						case 'RM-1': return {color: '#88CC88' };
						case 'RM-2': return {color: '#55AA55'};
						case 'RM-3': return {color: '#116611'};
						case 'RM-3/C': return {color: '#004400'};

						case 'RM-4': return {color: '#669999'};
						case 'RU-1': return {color: '#407F7F'};
						case 'RU-3': return {color: '#226666'};
						case 'RU-4': return {color: '#0D4D4D'};
						case 'RU-5': return {color: '#003333'};
						case 'CC-2': return { color: '#13073A'};
						case 'CN-2': return { color: '#FFAAAA'};
						case 'CN-3': return { color: '#D46A6A'};
						case 'CN-3/D-KP-1': return { color: '#AA3939'};
						case 'D-KP-4': return { color: '#801515'};
						case 'S-1': return { color: '#FFDB58'};
						case 'S-15': return { color: '#FFC900'};
        }
    }
}).addTo(map);
</script>

app/views/station/index.html.erb
<% @stations.each do |station| %>
	<img src="<%= static_map(station.as_latlng) %>" alt="Map of <%= station.name %>" />
	<a href="<%= station_path(station.gid)%>"><%= station.name %></a><br>
	<hr>
<% end %>

app/views/station/show.html.erb
<link rel="stylesheet" href="//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<script src="//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<style type="text/css">
	#map { height: 400px; } .legend{ list-style: none none; }
	.legend li.white{ color: white; }
	.legend li{
		display: inline;padding: 3px 3px 3px 3px;
	}
</style>
<h1>Parcels around <%= @station.name %></h1>
<ul class="legend">
	<li style="background-color:#88CC88">RM-1</li>
	<li style="background-color:#55AA55">RM-2</li>
	<li class="white" style="background-color:#116611">RM-3</li>
	<li class="white" style="background-color:#004400">RM-3/C</li>
	<li style="background-color:#669999">RM-4</li>
	<li style="background-color:#407F7F">RU-1</li>
	<li class="white" style="background-color:#226666">RU-3</li>
	<li class="white" style="background-color:#0D4D4D">RU-4</li>
	<li class="white" style="background-color:#003333">RU-5</li>
	<li class="white" style="background-color:#13073A">CC-2</li>
	<li style="background-color:#FFAAAA">CN-2</li>
	<li style="background-color:#D46A6A">CN-3</li>
	<li style="background-color:#AA3939">CN-3/D-KP-1</li>
	<li class="white" style="background-color:#801515">D-KP-4</li>
	<li style="background-color:#FFDB58">S-1</li>
	<li style="background-color:#FFC900">S-15</li>
	<li class="white" style="background-color:#1C51EE">not sure</li>
</ul>
<div id="map"></div>

<script type="text/javascript">
	var map = L.map('map').setView([<%= @station.as_latlng %>], 13);
	L.tileLayer('https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png', {
    maxZoom: 18
	}).addTo(map);
	L.geoJson(<%= raw @geo_json %>,  {
		onEachFeature: onEachFeature,
    style: function(feature) {
        switch (feature.properties.znlabel) {
						case 'RM-1': return {color: '#88CC88' };
						case 'RM-2': return {color: '#55AA55'};
						case 'RM-3': return {color: '#116611'};
						case 'RM-3/C': return {color: '#004400'};

						case 'RM-4': return {color: '#669999'};
						case 'RU-1': return {color: '#407F7F'};
						case 'RU-3': return {color: '#226666'};
						case 'RU-4': return {color: '#0D4D4D'};
						case 'RU-5': return {color: '#003333'};
						case 'CC-2': return { color: '#13073A'};
						case 'CN-2': return { color: '#FFAAAA'};
						case 'CN-3': return { color: '#D46A6A'};
						case 'CN-3/D-KP-1': return { color: '#AA3939'};
						case 'D-KP-4': return { color: '#801515'};
						case 'S-1': return { color: '#FFDB58'};
						case 'S-15': return { color: '#FFC900'};
        }
    }
}).addTo(map);
	function onEachFeature(feature, layer) {
    if (feature.properties) {
    		str = feature.properties.znlabel + '  <a href="/parcel/' + feature.properties.gid + '">Parcel Details</a>'
        layer.bindPopup(str);
    }
}

</script>